/*
 * 
 */
package machine;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Arrays;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hasimbola
 */
@SuppressWarnings("serial")
public class Application extends javax.swing.JFrame {
  JFrame f = new JFrame("Historique de tout les actions");
  JTable table = new JTable();
  String data[][] = new String[15][3];
  String columns[] = { "Date", "Action", "Montant" };
  
  JPanel panel = new JPanel();
  JScrollPane pane;
  private JavaHostApp host;
  private JFrame frame;
  static byte counter;
  int montant;
  static int i = 0;
  DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
  String date,action;
  boolean oui = true;
private String[] tab; 
  
    final static byte Wallet_CLA =(byte)0xB0;
  // codes of INS byte in the command APDU header
	final static byte VERIFY = (byte) 0x20;
	final static byte CREDIT = (byte) 0x30;
	final static byte DEBIT = (byte) 0x40;
	final static byte GET_BALANCE = (byte) 0x50;
	final static byte UNBLOCK = (byte) 0x60;
	final static byte INIT = (byte) 0x80;
	public static final byte CHANGE_PIN= 0x70;
    
    /**
     * Creates new form Application
     */
    public Application() {
        initComponents();
        host = new JavaHostApp();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	 jPanel1 = new javax.swing.JPanel();
         jTextField2 = new javax.swing.JTextField();
         jTextField3 = new javax.swing.JTextField();
         jTextField4 = new javax.swing.JTextField();
         jButton1 = new javax.swing.JButton();
         jButton2 = new javax.swing.JButton();
         jButton3 = new javax.swing.JButton();
         jLabel1 = new javax.swing.JLabel();
         jLabel2 = new javax.swing.JLabel();
         jLabel3 = new javax.swing.JLabel();
         jButton8 = new javax.swing.JButton();
         jLabel16 = new javax.swing.JLabel();
         jTextField16 = new javax.swing.JTextField();
         jButton9 = new javax.swing.JButton();
         jButton10 = new javax.swing.JButton();
         jPanel2 = new javax.swing.JPanel();
         jTextField1 = new javax.swing.JTextField();
         jLabel4 = new javax.swing.JLabel();
         jTextField5 = new javax.swing.JTextField();
         jLabel5 = new javax.swing.JLabel();
         jTextField6 = new javax.swing.JTextField();
         jTextField7 = new javax.swing.JTextField();
         jTextField8 = new javax.swing.JTextField();
         jTextField9 = new javax.swing.JTextField();
         jTextField10 = new javax.swing.JTextField();
         jLabel6 = new javax.swing.JLabel();
         jLabel7 = new javax.swing.JLabel();
         jLabel8 = new javax.swing.JLabel();
         jLabel9 = new javax.swing.JLabel();
         jLabel10 = new javax.swing.JLabel();
         jButton5 = new javax.swing.JButton();
         jLabel11 = new javax.swing.JLabel();
         jTextField11 = new javax.swing.JTextField();
         jTextField12 = new javax.swing.JTextField();
         jTextField13 = new javax.swing.JTextField();
         jLabel12 = new javax.swing.JLabel();
         jLabel13 = new javax.swing.JLabel();
         jLabel14 = new javax.swing.JLabel();
         jLabel15 = new javax.swing.JLabel();
         jButton6 = new javax.swing.JButton();
         jTextField14 = new javax.swing.JTextField();
         jTextField15 = new javax.swing.JTextField();
         jButton7 = new javax.swing.JButton();

         setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

         jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Actions externes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

         jTextField2.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 jTextField2ActionPerformed(evt);
             }
         });

         jTextField3.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 jTextField3ActionPerformed(evt);
             }
         });

         jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
         jButton1.setText("Credit");
         jButton1.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 jButton1ActionPerformed(evt);
             }
         });

         jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
         jButton2.setText("Debit");
         jButton2.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 jButton2ActionPerformed(evt);
             }
         });

         jButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
         jButton3.setText("Balance");
         jButton3.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 jButton3ActionPerformed(evt);
             }
         });

         jLabel1.setText("Montant a crediter ");

         jLabel2.setText("Montant a debiter");

         jLabel3.setText("La valeur du compte");

         jButton8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
         jButton8.setText("Changer PIN");
         jButton8.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 jButton8ActionPerformed(evt);
             }
         });

         jLabel16.setText("Initialiser");

         jButton9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
         jButton9.setText("Initialiser");
         jButton9.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 jButton9ActionPerformed(evt);
             }
         });

         jButton10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
         jButton10.setText("Historique");
         jButton10.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
            	 jButton10ActionPerformed(evt);
             }
         });

         javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
         jPanel1.setLayout(jPanel1Layout);
         jPanel1Layout.setHorizontalGroup(
             jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(jPanel1Layout.createSequentialGroup()
                 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(jPanel1Layout.createSequentialGroup()
                         .addGap(135, 135, 135)
                         .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                             .addComponent(jLabel2)
                             .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                             .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                             .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                         .addGap(72, 72, 72)
                         .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                             .addComponent(jTextField16, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                             .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                             .addComponent(jTextField2)
                             .addComponent(jTextField3))
                         .addGap(0, 0, Short.MAX_VALUE))
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                         .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                         .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addGap(26, 26, 26)
                         .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addGap(18, 18, 18)
                         .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                             .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                             .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                         .addComponent(jButton8)
                         .addGap(18, 18, 18)
                         .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                 .addContainerGap())
         );
         jPanel1Layout.setVerticalGroup(
             jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(jPanel1Layout.createSequentialGroup()
                 .addGap(32, 32, 32)
                 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                 .addGap(18, 18, 18)
                 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                 .addGap(18, 18, 18)
                 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                 .addGap(18, 18, 18)
                 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                 .addGap(18, 18, 18)
                 .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
         );

         jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Actions internes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

         jTextField1.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 jTextField1ActionPerformed(evt);
             }
         });

         jLabel4.setText("CLA");

         jTextField5.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 jTextField5ActionPerformed(evt);
             }
         });

         jLabel5.setText("INS");

         jTextField6.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 jTextField6ActionPerformed(evt);
             }
         });

         jTextField9.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 jTextField9ActionPerformed(evt);
             }
         });

         jTextField10.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 jTextField10ActionPerformed(evt);
             }
         });

         jLabel6.setText("P1");

         jLabel7.setText("P2");

         jLabel8.setText("Lc");

         jLabel9.setText("Data Field");

         jLabel10.setText("Le");

         jButton5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
         jButton5.setText("Establish Connection with CardReader Simulator");
         jButton5.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 jButton5ActionPerformed(evt);
             }
         });

         jLabel11.setText("Response APDU");

         jTextField12.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 jTextField12ActionPerformed(evt);
             }
         });

         jTextField13.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 jTextField13ActionPerformed(evt);
             }
         });

         jLabel12.setText("SW2");

         jLabel13.setText("SW1");

         jLabel14.setText("Data Field");

         jLabel15.setText("Command APDU");

         jButton6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
         jButton6.setText("Close the Connection with CardReader Simulator");
         jButton6.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 jButton6ActionPerformed(evt);
             }
         });

         jTextField14.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 jTextField14ActionPerformed(evt);
             }
         });

         jButton7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
         jButton7.setText("Unblock Card");
         jButton7.addActionListener(new java.awt.event.ActionListener() {
             public void actionPerformed(java.awt.event.ActionEvent evt) {
                 jButton7ActionPerformed(evt);
             }
         });

         javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
         jPanel2.setLayout(jPanel2Layout);
         jPanel2Layout.setHorizontalGroup(
             jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(jPanel2Layout.createSequentialGroup()
                         .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                             .addGroup(jPanel2Layout.createSequentialGroup()
                                 .addContainerGap()
                                 .addComponent(jTextField11)
                                 .addGap(18, 18, 18))
                             .addGroup(jPanel2Layout.createSequentialGroup()
                                 .addGap(37, 37, 37)
                                 .addComponent(jLabel14)
                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                         .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                             .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                 .addComponent(jLabel13)
                                 .addGap(34, 34, 34))
                             .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                 .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                 .addGap(18, 18, 18))))
                     .addGroup(jPanel2Layout.createSequentialGroup()
                         .addContainerGap()
                         .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                             .addGroup(jPanel2Layout.createSequentialGroup()
                                 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                     .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                     .addGroup(jPanel2Layout.createSequentialGroup()
                                         .addGap(9, 9, 9)
                                         .addComponent(jLabel4)))
                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                     .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                         .addComponent(jLabel5)
                                         .addGap(15, 15, 15)))
                                 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                     .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                         .addComponent(jLabel6)
                                         .addGap(16, 16, 16)))
                                 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                     .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                         .addComponent(jLabel7)
                                         .addGap(16, 16, 16)))
                                 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                     .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                     .addGroup(jPanel2Layout.createSequentialGroup()
                                         .addGap(11, 11, 11)
                                         .addComponent(jLabel8)))
                                 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                     .addGroup(jPanel2Layout.createSequentialGroup()
                                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                         .addComponent(jTextField10)
                                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                         .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                         .addGap(108, 108, 108))))
                             .addGroup(jPanel2Layout.createSequentialGroup()
                                 .addComponent(jButton7)
                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                     .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                     .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                 .addGap(28, 28, 28)))))
                 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(jTextField13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                     .addComponent(jTextField9)
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                         .addComponent(jLabel10)
                         .addGap(12, 12, 12))
                     .addGroup(jPanel2Layout.createSequentialGroup()
                         .addGap(8, 8, 8)
                         .addComponent(jLabel12))
                     .addComponent(jTextField14)
                     .addComponent(jTextField15))
                 .addGap(34, 34, 34))
             .addGroup(jPanel2Layout.createSequentialGroup()
                 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(jPanel2Layout.createSequentialGroup()
                         .addGap(229, 229, 229)
                         .addComponent(jLabel11))
                     .addGroup(jPanel2Layout.createSequentialGroup()
                         .addGap(227, 227, 227)
                         .addComponent(jLabel15)))
                 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
         );
         jPanel2Layout.setVerticalGroup(
             jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(jPanel2Layout.createSequentialGroup()
                 .addGap(16, 16, 16)
                 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel4)
                     .addComponent(jLabel5)
                     .addComponent(jLabel6)
                     .addComponent(jLabel7)
                     .addComponent(jLabel8)
                     .addComponent(jLabel9)
                     .addComponent(jLabel10))
                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                 .addGap(4, 4, 4)
                 .addComponent(jLabel15)
                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabel14)
                     .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel12)
                         .addComponent(jLabel13)))
                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                 .addComponent(jLabel11)
                 .addGap(26, 26, 26)
                 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jButton5)
                     .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jButton7))
                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jButton6))
                 .addContainerGap(29, Short.MAX_VALUE))
         );

         javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
         getContentPane().setLayout(layout);
         layout.setHorizontalGroup(
             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(layout.createSequentialGroup()
                 .addContainerGap()
                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                 .addContainerGap())
         );
         layout.setVerticalGroup(
             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(layout.createSequentialGroup()
                 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                 .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                 .addGap(31, 31, 31)
                 .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                 .addContainerGap())
         );

         jPanel1.getAccessibleContext().setAccessibleName("GeldAutomat\n");

         pack();
     }// </editor-fold>                                           

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {   
    }                                           
    
        
    /*ACTION CREDITER*/    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        String mdp =  JOptionPane.showInputDialog(frame, "Entrer votre PIN");
        
        //verify
        byte lengthDataField1 = 4;
        byte maxDataBytesExpected1 = 0;
        byte instParamtr11 = 0;
        byte instParamtr21 = 0;  
      
        char[] ip = mdp.toCharArray();
        byte[] data_z = new byte[ip.length];
       

        byte[] cmnds_z = {Wallet_CLA, VERIFY, instParamtr11, instParamtr21};
        host.setTheAPDUCommands(cmnds_z);
        host.setTheDataLength(lengthDataField1);
        
        for(int ipIndx = 0; ipIndx<ip.length;ipIndx++){
            data_z[ipIndx] = (byte)(ip[ipIndx]&0x0F);
        }
        host.setTheDataIn(data_z);
        host.setExpctdByteLength(maxDataBytesExpected1);
        setTheCommandAPDUOnGUI(cmnds_z, data_z,lengthDataField1, maxDataBytesExpected1);
        host.exchangeTheAPDUWithSimulator();
        host.decodeStatus();  
        setTheResponseAPDUOnGUI(maxDataBytesExpected1);
      
        date = dtf.format(LocalDateTime.now());
        montant = Integer.parseInt(jTextField2.getText());
        
        System.err.println("Credit");
        //credit
        byte lengthDataField = 1;
        byte maxDataBytesExpected = 0;
        byte instParamtr1 = 0;
        byte instParamtr2 = 0;
        
        byte[] cmnds_c = {Wallet_CLA, CREDIT, instParamtr1, instParamtr2};
        host.setTheAPDUCommands(cmnds_c);
        host.setTheDataLength(lengthDataField);
        try{
        byte[] data_c = {(byte)Integer.parseInt(jTextField2.getText())};
        host.setTheDataIn(data_c);
        host.setExpctdByteLength(maxDataBytesExpected);
        setTheCommandAPDUOnGUI(cmnds_c, data_c,lengthDataField, maxDataBytesExpected);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(frame, "PLEASE ENTER A VALID INPUT.");
        }        
        host.exchangeTheAPDUWithSimulator();
        host.decodeStatus(); 
        setTheResponseAPDUOnGUI(maxDataBytesExpected);
        setDataInTable(date,"Credit",montant);
    }                                        

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {    
    }                                           

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {     
        
        byte lengthDataField = 6;
        byte maxDataBytesExpected = 0;
        byte instParamtr1 = 0x04;
        byte instParamtr2 = 0;  
        counter = 3;
        
        host.establishConnectionToSimulator();
        host.pwrUp();
         //select
        byte[] cmnds = {(byte)0x00, (byte)0xA4, instParamtr1, instParamtr2};       
        host.setTheAPDUCommands(cmnds);
        host.setTheDataLength(lengthDataField);
        byte[] data = {(byte)0x7C, (byte)0x0F, (byte)0x1B, (byte)0x01, (byte)0x88, (byte)0x01};
        host.setTheDataIn(data);
        host.setExpctdByteLength(maxDataBytesExpected);
        setTheCommandAPDUOnGUI(cmnds, data,lengthDataField, maxDataBytesExpected);
        host.exchangeTheAPDUWithSimulator();
        host.decodeStatus();
        setTheResponseAPDUOnGUI(maxDataBytesExpected);
        
        jTextField14.setText("Done");
        jTextField15.setText("");
     
    }                                        

    
    
    
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {  
    }                                           

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) { 
    }                                           

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {  
    }                                           

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {  
    }                                            

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {  
    }                                           

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) { 
    }                                            

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {   
    }                                            

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {   
        host.pwrDown();
        host.closeConnection();
        jTextField14.setText("");
        jTextField15.setText("Done");
        
    }                                        

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {   
    }                                            

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {  
        
        System.err.println("Unblock");
        //unblock
        byte lengthDataField = 1;
        byte maxDataBytesExpected = 0;
        byte instParamtr1 = 0;
        byte instParamtr2 = 0;
        counter = 3;
        
        byte[] cmnds_u = {Wallet_CLA, UNBLOCK, instParamtr1, instParamtr2};
        host.setTheAPDUCommands(cmnds_u);
        host.setTheDataLength(lengthDataField);
        byte[] data_u = {(byte)0x7F};
        host.setTheDataIn(data_u);
        host.setExpctdByteLength(maxDataBytesExpected);
        setTheCommandAPDUOnGUI(cmnds_u, data_u,lengthDataField, maxDataBytesExpected);   
        host.exchangeTheAPDUWithSimulator();
        host.decodeStatus(); 
        setTheResponseAPDUOnGUI(maxDataBytesExpected);
        
        
    }                                        

    
    /*DEBITER UNE VALEUR*/
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        String mdp =  JOptionPane.showInputDialog(frame, "Entrer votre PIN");
        
        //verify
        byte lengthDataField1 = 4;
        byte maxDataBytesExpected1 = 0;
        byte instParamtr11 = 0;
        byte instParamtr21 = 0;  
      
        char[] ip = mdp.toCharArray();
        byte[] data_x = new byte[ip.length];
       

        byte[] cmnds_x = {Wallet_CLA, VERIFY, instParamtr11, instParamtr21};
        host.setTheAPDUCommands(cmnds_x);
        host.setTheDataLength(lengthDataField1);
        
        for(int ipIndx = 0; ipIndx<ip.length;ipIndx++){
            data_x[ipIndx] = (byte)(ip[ipIndx]&0x0F);
        }
        host.setTheDataIn(data_x);
        host.setExpctdByteLength(maxDataBytesExpected1);
        setTheCommandAPDUOnGUI(cmnds_x, data_x,lengthDataField1, maxDataBytesExpected1);
        host.exchangeTheAPDUWithSimulator();
        host.decodeStatus();  
        setTheResponseAPDUOnGUI(maxDataBytesExpected1);        
        
        
        date = dtf.format(LocalDateTime.now());
        montant = Integer.parseInt(jTextField3.getText());
        
        System.err.println("Debit");
        //DEBIT
        byte lengthDataField = 1;
        byte maxDataBytesExpected = 0;
        byte instParamtr1 = 0;
        byte instParamtr2 = 0;
        
        byte[] cmnds_e = {Wallet_CLA, DEBIT, instParamtr1, instParamtr2};
        host.setTheAPDUCommands(cmnds_e);
        host.setTheDataLength(lengthDataField);
        try{
        byte[] data_e = {(byte)Integer.parseInt(jTextField3.getText())};
        host.setTheDataIn(data_e);
        host.setExpctdByteLength(maxDataBytesExpected);
        setTheCommandAPDUOnGUI(cmnds_e, data_e,lengthDataField, maxDataBytesExpected);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(frame, "Entrer un montant valide");
        }        
        host.exchangeTheAPDUWithSimulator();
        host.decodeStatus(); 
        setTheResponseAPDUOnGUI(maxDataBytesExpected);
        setDataInTable(date,"Debit",montant);
    }                                        

    
    /*CONSULTER LE SOLDE*/
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) { 
        
        String mdp =  JOptionPane.showInputDialog(frame, "Entrer votre PIN");
        
        //verify
        byte lengthDataField1 = 4;
        byte maxDataBytesExpected1 = 0;
        byte instParamtr11 = 0;
        byte instParamtr21 = 0;  
      
        char[] ip = mdp.toCharArray();
        byte[] data_v = new byte[ip.length];
       

        byte[] cmnds_v = {Wallet_CLA, VERIFY, instParamtr11, instParamtr21};
        host.setTheAPDUCommands(cmnds_v);
        host.setTheDataLength(lengthDataField1);
        
        for(int ipIndx = 0; ipIndx<ip.length;ipIndx++){
            data_v[ipIndx] = (byte)(ip[ipIndx]&0x0F);
        }
        host.setTheDataIn(data_v);
        host.setExpctdByteLength(maxDataBytesExpected1);
        setTheCommandAPDUOnGUI(cmnds_v, data_v,lengthDataField1, maxDataBytesExpected1);
        host.exchangeTheAPDUWithSimulator();
        host.decodeStatus();  
        setTheResponseAPDUOnGUI(maxDataBytesExpected1);
        
         System.err.println("Balance");
        //balance
        byte lengthDataField = 1;
        byte maxDataBytesExpected = 2;
        byte instParamtr1 = 0;
        byte instParamtr2 = 0;
        
        byte[] cmnds_b = {Wallet_CLA, GET_BALANCE, instParamtr1, instParamtr2};
        host.setTheAPDUCommands(cmnds_b);
        host.setTheDataLength(lengthDataField);
        
        byte[] data_b = {(byte)0x7F};
        host.setTheDataIn(data_b);
        host.setExpctdByteLength(maxDataBytesExpected);
        setTheCommandAPDUOnGUI(cmnds_b, data_b,lengthDataField, maxDataBytesExpected);              
        host.exchangeTheAPDUWithSimulator();
        host.decodeStatus();
        host.decodeDataOut();
        setTheResponseAPDUOnGUI(maxDataBytesExpected);
        setHistorique(cmnds_b);
        
    }                                        
    
    /*CHANGER LE PIN*/
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        String mdp =  JOptionPane.showInputDialog(frame, "Entrer votre PIN");
        
        byte lengthDataField2 = 4;
        byte maxDataBytesExpected2 = 0;
        byte instParamtr12 = 0;
        byte instParamtr22 = 0;  
      
        char[] ip = mdp.toCharArray();
        byte[] data_g = new byte[ip.length];

        byte[] cmnds_g = {Wallet_CLA, CHANGE_PIN, instParamtr12, instParamtr22};
        host.setTheAPDUCommands(cmnds_g);
        host.setTheDataLength(lengthDataField2);
        
        for(int ipIndx = 0; ipIndx<ip.length;ipIndx++){
            data_g[ipIndx] = (byte)(ip[ipIndx] & 0x0F);
        }
        
        host.setTheDataIn(data_g);
        host.setExpctdByteLength(maxDataBytesExpected2);
        setTheCommandAPDUOnGUI(cmnds_g, data_g,lengthDataField2, maxDataBytesExpected2);
        host.exchangeTheAPDUWithSimulator();
        host.decodeStatus();  
        setTheResponseAPDUOnGUI(maxDataBytesExpected2);
    }                                        

    
    /*INITIALISER*/
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {  
        String mdp =  JOptionPane.showInputDialog(frame, "Entrer votre PIN");
        
        //verify
        byte lengthDataField1 = 4;
        byte maxDataBytesExpected1 = 0;
        byte instParamtr11 = 0;
        byte instParamtr21 = 0;  
      
        char[] ip = mdp.toCharArray();
        byte[] data_i = new byte[ip.length];
       

        byte[] cmnds_i = {Wallet_CLA, VERIFY, instParamtr11, instParamtr21};
        host.setTheAPDUCommands(cmnds_i);
        host.setTheDataLength(lengthDataField1);
        
        for(int ipIndx = 0; ipIndx<ip.length;ipIndx++){
            data_i[ipIndx] = (byte)(ip[ipIndx]&0x0F);
        }
        host.setTheDataIn(data_i);
        host.setExpctdByteLength(maxDataBytesExpected1);
        setTheCommandAPDUOnGUI(cmnds_i, data_i,lengthDataField1, maxDataBytesExpected1);
        host.exchangeTheAPDUWithSimulator();
        host.decodeStatus();  
        setTheResponseAPDUOnGUI(maxDataBytesExpected1);
        
        date = dtf.format(LocalDateTime.now());
        montant = Integer.parseInt(jTextField16.getText());
        
         System.err.println("Initialiser");
         
           //INITIALISER
           byte lengthDataField = 1;
           byte maxDataBytesExpected = 0;
           byte instParamtr1 = 0;
           byte instParamtr2 = 0;
           
           byte[] cmnds_l = {Wallet_CLA, INIT, instParamtr1, instParamtr2};
           host.setTheAPDUCommands(cmnds_l);
           host.setTheDataLength(lengthDataField);
           try{
           byte[] data_l = {(byte)Integer.parseInt(jTextField16.getText())};
           host.setTheDataIn(data_l);
           host.setExpctdByteLength(maxDataBytesExpected);
           setTheCommandAPDUOnGUI(cmnds_l, data_l,lengthDataField, maxDataBytesExpected);
           }catch(NumberFormatException e){
               JOptionPane.showMessageDialog(frame, "Entrer un montant valide");
           }        
           host.exchangeTheAPDUWithSimulator();
           host.decodeStatus(); 
           setTheResponseAPDUOnGUI(maxDataBytesExpected);
           setDataInTable(date,"Initialiser",montant);
    }          
    
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {  
    	 try
    	    {
    	      // Le fichier d'entrée
    	      File file = new File("file.txt");    
    	      // Créer l'objet File Reader
    	      FileReader fr = new FileReader(file);  
    	      // Créer l'objet BufferedReader        
    	      BufferedReader br = new BufferedReader(fr);  
    	      StringBuffer sb = new StringBuffer();    
    	      String line;
    	      while((line = br.readLine()) != null)
    	      {
    	        // ajoute la ligne au buffer
    	        sb.append(line);  
    	        sb.append("\n");  
    	        String [] tab=line.split("-");
    	        data[i][0] = tab[0];
    	        data[i][1] = tab[1];
    	        data[i][2] = tab[2];
    	        DefaultTableModel model = new DefaultTableModel(data, columns);
   	         	table.setModel(model);
   	         	table.setShowVerticalLines(true);
   	         	i++;
   		      
   	         	model.setRowCount(i);
   	         	pane = new JScrollPane(table);
    	        System.out.println(tab[1]);
    	      }
    	      
    	      fr.close();    
    	      
    	      System.out.println("Contenu du fichier: ");
    	      System.out.println(sb.toString());  
    	    }
    	    catch(IOException e)
    	    {
    	      e.printStackTrace();
    	    }
		
		     // table.setShowGrid(true);
	        
         	f.add(pane);
	    	f.setSize(500, 250);
	    	f.setResizable(false);
		    f.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    		f.setVisible(true);
    }   

    
    public void setTheCommandAPDUOnGUI(byte [] cmnds, byte [] data, byte lc, byte le){
        
        jTextField1.setText("0x"+String.valueOf(host.atrToHex(cmnds[0])));
        jTextField5.setText("0x"+String.valueOf(host.atrToHex(cmnds[1])));
        jTextField6.setText("0x"+String.valueOf(host.atrToHex(cmnds[2])));
        jTextField7.setText("0x"+String.valueOf(host.atrToHex(cmnds[3])));
        jTextField8.setText("0x"+String.valueOf(lc));
        
        String temp = "";
        for(int i = 0; i<data.length;i++){
            temp += "0x"+host.atrToHex(data[i]);
            temp += " ";
           
        }
        
        jTextField10.setText(temp);
        jTextField9.setText("0x"+String.valueOf(le));
        
    }
    
     public void setTheResponseAPDUOnGUI(byte le){
        
        byte[] stat = host.decodeStatus();
        jTextField12.setText("0x"+String.valueOf(host.atrToHex(stat[0])));
        jTextField13.setText("0x"+String.valueOf(host.atrToHex(stat[1])));
        
        
        String caseCmnd = host.atrToHex(stat[0])+host.atrToHex(stat[1]);
        if(caseCmnd.matches("6311")){
            JOptionPane.showMessageDialog(frame, "PIN VERIFICATION REQUIRED.");
        }else if(caseCmnd.matches("6A83")){
            JOptionPane.showMessageDialog(frame, "INVALID TRANSACTION AMOUNT.");
        }else if(caseCmnd.matches("6A84")){
            JOptionPane.showMessageDialog(frame, "EXCEED MAXIMUM BALANCE .");
        }else if(caseCmnd.matches("6A85")){
            JOptionPane.showMessageDialog(frame, "NEGATIVE BALANCE.");
        }else if(caseCmnd.matches("6312") && counter > 0){
            JOptionPane.showMessageDialog(frame, "Wrong PIN "+String.valueOf(--counter)+" attempts left");
        }else if(counter<=0){
            JOptionPane.showMessageDialog(frame, "Card has been blocked!!!!");
        }
        byte[] dataOut = host.decodeDataOut();
        if(le!=0 && dataOut.length != 0){
        //set the balance on textview
        jTextField4.setText(String.valueOf(Integer.parseInt(host.atrToHex(dataOut[0]), 16))+ String.valueOf(Integer.parseInt(host.atrToHex(dataOut[1]), 16)));
        //set the dataout on textview
        jTextField11.setText("0x"+String.valueOf(host.atrToHex(dataOut[0])) + " " + "0x"+String.valueOf(host.atrToHex(dataOut[1])));
        }
    }
     
     public void  setHistorique(byte [] cmnds) {
    	 String fileName = "my-file.txt";
    	 String encoding = "UTF-8";
    	 try{
    	    PrintWriter writer = new PrintWriter(fileName, encoding);
    	    writer.println("CLA = "+"0x"+String.valueOf(host.atrToHex(cmnds[0])));
    	    writer.println("INS = "+"0x"+String.valueOf(host.atrToHex(cmnds[1])));
    	    writer.println("P1 =  "+"0x"+String.valueOf(host.atrToHex(cmnds[2])));
    	    writer.println("P2 =  "+"0x"+String.valueOf(host.atrToHex(cmnds[3])));
    	    writer.close();
    	    }
    	    catch (IOException e){
    	      System.out.println("An error occurred.");
    	      e.printStackTrace();
    	 }
     }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            	Application window = new Application();
                window.setVisible(true);
                window.setLocation(625, 150);
            }
        });
    }

    public void setDataInTable(String date,String action,int montant) {
    	try
    	{
    	 String filename="file.txt";
    	 FileWriter fw = new FileWriter(filename,true);
    	 fw.write(date +"-"+ action +"-"+ montant);
    	 fw.append("\n");
    	 fw.close();
    	}
    	catch(IOException ioe)
    	{
    	 System.err.println(ioe.getMessage());
    	}
//	 	 String fileName = "file.txt";
//         Scanner scan;
//		 try {
//			scan = new Scanner(new File(fileName));
//			  while(scan.hasNextLine()){
//		             String line = scan.nextLine();
//		             tab =line.split("-"); 
//		             System.out.println(Arrays.toString(tab));
//		             System.out.println(line);
//		         }
//		} catch (FileNotFoundException e) {
//			// TODO Auto-generated catch block
//			e.printStackTrace();
//		}
		 
		 try
		    {
		      // Le fichier d'entrée
		      File file = new File("file.txt");    
		      // Créer l'objet File Reader
		      FileReader fr = new FileReader(file);  
		      // Créer l'objet BufferedReader        
		      BufferedReader br = new BufferedReader(fr);  
		      StringBuffer sb = new StringBuffer();    
		      String line;
		      while((line = br.readLine()) != null)
		      {
		        // ajoute la ligne au buffer
		        sb.append(line);      
		        sb.append("\n");     
		      }
		      fr.close();    
		      System.out.println("Contenu du fichier: ");
		      System.out.println(Arrays.toString(tab));
		      System.out.println(sb.toString());  
		    }
		    catch(IOException e)
		    {
		      e.printStackTrace();
		    }

//		
//			data[i][0] = tab[0];
//	        data[i][1] = tab[1];
//	        data[i][2] = tab[2];
//	        	     
//		     // table.setShowGrid(true);
//	         DefaultTableModel model = new DefaultTableModel(data, columns);
//	         table.setModel(model);
//		     table.setShowVerticalLines(true);
//		      i++;
//		      
//		      model.setRowCount(i);
//		      JScrollPane pane = new JScrollPane(table); 
//		      
//		      panel.add(pane);
//		      f.add(panel);
		      
    	/*CODE ANDRANA VAOVAO*/
    	
    
		
    }
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration                   
}